services:
  web1:
    image: web1
    network_mode: "host"
  web2:
    image: web2
    network_mode: "host"
  nginx:
    image: nginx:1.27-alpine
    network_mode: "host"
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert:/etc/nginx/certs:ro