services:

  web1:
    image: web1
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5001

  web2:
    image: web2
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5002

  nginx:
    image: nginx:1.27-alpine
    network_mode: "host"
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert:/etc/nginx/certs:ro